import { useMemo, useRef, useState, type CSSProperties } from "react";
import { Link } from "react-router-dom";
import type { Square } from "react-chessboard/dist/chessboard/types";
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight, Copy, Download, FlipVertical, FolderClock, MoreHorizontal, Plus, Redo2, Save, Settings2, Undo2, Upload, X } from "lucide-react";
import ChessBoard from "@/components/ChessBoard";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { retryStockfishWorker } from "@/lib/stockfish";
import { EvalBar, EvaluationGraph } from "./EvaluationGraph";
import { MoveTree } from "./MoveTree";
import { PositionEditor } from "./PositionEditor";
import { ReviewPanel } from "./ReviewPanel";
import { ENGINE_LEVELS, type EngineLevel } from "./usePositionEngine";
import { newDocument, pvMoves, updateTree } from "./tree";
import { copyText, useAnalysisWorkspace } from "./useAnalysisWorkspace";
import "./analysis.css";

const HEADER_LABELS: Record<string, string> = { White: "Білі", Black: "Чорні", WhiteElo: "Рейтинг білих", BlackElo: "Рейтинг чорних", Result: "Результат", TimeControl: "Контроль часу", Date: "Дата", Event: "Подія", Site: "Місце", ECO: "Код дебюту" };
export default function AnalysisCenter() {
  const w = useAnalysisWorkspace();
  const fileInput = useRef<HTMLInputElement>(null), [jump, setJump] = useState("");
  const arrowMove = !w.preview && w.bestArrow && w.engineEnabled ? w.engine.result?.bestmove : null;
  const arrows = useMemo<[Square, Square, string][]>(() => arrowMove ? [[arrowMove.slice(0, 2) as Square, arrowMove.slice(2, 4) as Square, "#22458f"]] : [], [arrowMove]);
  const lastSquares = useMemo<Square[]>(() => !w.preview && w.selected.uci ? [w.selected.uci.slice(0, 2) as Square, w.selected.uci.slice(2, 4) as Square] : [], [w.preview, w.selected.uci]);
  const player = (color: "w" | "b") => {
    const name = w.document.headers[color === "w" ? "White" : "Black"], rating = w.document.headers[color === "w" ? "WhiteElo" : "BlackElo"];
    return <div className="analysis-player"><span className={`analysis-side is-${color}`} aria-hidden="true"/><strong>{name && name !== "?" ? name : color === "w" ? "Білі" : "Чорні"}</strong>{rating && rating !== "?" && <span>{rating}</span>}<span className="analysis-player-turn">{w.displayedFen.split(" ")[1] === color ? "Хід" : ""}</span></div>;
  };
  const headers = Object.entries(w.document.headers).filter(([key]) => key !== "FEN" && key !== "SetUp");
  return <div className="analysis-center">
    <header className="analysis-heading"><div><h1>Аналіз партії</h1><p>{w.opening ? `${w.opening.eco} · ${w.opening.name}` : "Дослідіть позицію та перевірте свої ідеї"}</p></div><div className="analysis-heading-actions">
      <Button variant="outline" onClick={() => w.setImportOpen(true)}><Upload size={16}/>Імпорт</Button>
      <Button variant="outline" onClick={() => w.setEditorOpen(true)}><Plus size={16}/>Нова позиція</Button>
      <Button variant="outline" onClick={w.download} aria-label="Завантажити PGN"><Download size={16}/><span className="analysis-desktop-label">PGN</span></Button>
      <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" aria-label="Інші дії аналізу"><MoreHorizontal size={20}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => void copyText(w.fullPgn)}>Копіювати PGN</DropdownMenuItem><DropdownMenuItem onSelect={() => void copyText(w.displayedFen)}>Копіювати FEN</DropdownMenuItem><DropdownMenuItem onSelect={() => { w.review.cancel(); w.replace(newDocument()); w.navigate("/analysis", { replace: true, state: null }); }}>Відкрити новий аналіз</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
    </div></header>
    {w.loadError && <div className="analysis-error" role="alert">{w.loadError}<Button variant="link" onClick={() => w.setImportOpen(true)}>Імпортувати PGN</Button></div>}
    <div className="analysis-layout">
      <section ref={w.boardArea} className="analysis-board-area" aria-label="Дошка аналізу"><div className="analysis-board-column" style={{ "--analysis-board-size": `${w.boardSize}px` } as CSSProperties}>
        {player(w.flipped ? "w" : "b")}
        <div className="analysis-board-row">{w.engineEnabled && <EvalBar score={w.score} flipped={w.flipped}/>} {w.busy ? <Skeleton style={{ width: w.boardSize, height: w.boardSize }} aria-label="Завантаження партії"/> : <ChessBoard key={w.arrowsEpoch} initialFen={w.displayedFen} size={w.boardSize} flipped={w.flipped} onMove={w.boardMove} interactive={!w.preview} optimistic={false} customArrows={arrows} allowArrows showLegalMoves showLastMove lastMoveSquares={lastSquares}/> }</div>
        {player(w.flipped ? "b" : "w")}
        {w.preview && <div className="analysis-preview-status"><span>Перегляд варіанта · {w.preview.index + 1}/{w.preview.moves.length}</span><Button size="sm" variant="ghost" onClick={() => w.setPreview(null)}><X size={14}/>До партії</Button></div>}
        <div className="analysis-board-controls"><Button variant="ghost" size="icon" aria-label="На початок" onClick={() => w.navigateMove("first")}><ChevronsLeft size={20}/></Button><Button variant="ghost" size="icon" aria-label="Попередній хід" onClick={() => w.navigateMove("previous")}><ChevronLeft size={20}/></Button><Button variant="ghost" size="icon" aria-label="Наступний хід" onClick={() => w.navigateMove("next")}><ChevronRight size={20}/></Button><Button variant="ghost" size="icon" aria-label="У кінець" onClick={() => w.navigateMove("last")}><ChevronsRight size={20}/></Button><span/><Button variant="ghost" size="icon" aria-label="Перевернути дошку" onClick={() => w.setFlipped(value => !value)}><FlipVertical size={18}/></Button><Button variant="ghost" size="icon" aria-label="Налаштування аналізу" onClick={() => w.setSettingsOpen(true)}><Settings2 size={18}/></Button></div>
      </div></section>
      <aside className="analysis-panel surface" aria-label="Інструменти аналізу">
        <div className="analysis-panel-top"><span>{w.document.headers.Result && w.document.headers.Result !== "*" ? w.document.headers.Result.replace("1/2-1/2", "½–½") : w.line.length ? `${w.line.length} півходів` : "Нова позиція"}</span><div className="analysis-engine-switch"><label htmlFor="engine-switch">Движок</label><Switch id="engine-switch" checked={w.engineEnabled} onCheckedChange={w.setEngineEnabled}/></div></div>
        <Tabs value={w.tab} onValueChange={w.setTab} className="analysis-tabs"><TabsList className="analysis-tab-list"><TabsTrigger value="overview">Огляд</TabsTrigger><TabsTrigger value="moves">Ходи</TabsTrigger><TabsTrigger value="engine">Движок</TabsTrigger><TabsTrigger value="info">Інфо</TabsTrigger></TabsList>
          <TabsContent value="overview" className="analysis-tab-content"><ReviewPanel report={w.review.report} running={w.running} completed={w.review.completed} total={w.review.total} error={w.review.error} hasMoves={!!w.line.length} selectedMove={w.reviewedMove} onStart={force => { retryStockfishWorker(); void w.review.start(force); }} onCancel={w.review.cancel} onSelect={w.selectIndex} onBest={w.showBest} onCategory={category => { const moves = w.review.report?.moves.filter(move => move.classification === category) || []; const next = moves.find(move => move.index > w.index) || moves[0]; if (next) w.selectIndex(next.index); }}/></TabsContent>
          <TabsContent value="moves" className="analysis-tab-content">
            {!w.loaded && !w.line.length && <div className="analysis-import-empty"><h2>Відкрийте партію</h2><p>PGN збереже ходи, варіанти й коментарі. FEN відкриє окрему позицію.</p><Button onClick={() => w.setImportOpen(true)}>Вставити PGN або FEN</Button></div>}
            <MoveTree document={w.document} selected={w.selected} report={w.review.report} onSelect={w.select} onComment={text => w.mutate(current => updateTree(current, w.selected.id, node => { node.comment = text; }))} onDelete={w.deleteBranch} onPromote={w.promote} onCopy={w.copyBranch}/>
            <div className="analysis-edit-controls"><Button variant="ghost" size="icon" aria-label="Скасувати зміну" disabled={!w.undo.length} onClick={() => w.history(true)}><Undo2 size={17}/></Button><Button variant="ghost" size="icon" aria-label="Повторити зміну" disabled={!w.redo.length} onClick={() => w.history(false)}><Redo2 size={17}/></Button><form onSubmit={event => { event.preventDefault(); const index = w.line.findIndex((_, i) => Number((i ? w.line[i - 1].fen : w.document.root.fen).split(" ")[5]) === Number(jump)); if (index >= 0) w.selectIndex(index); }}><Input type="number" min="1" value={jump} onChange={event => setJump(event.target.value)} aria-label="Номер ходу" placeholder="Хід"/><Button variant="ghost" size="sm" type="submit">Перейти</Button></form></div>
          </TabsContent>
          <TabsContent value="engine" className="analysis-tab-content"><div className="analysis-engine-panel"><div className="analysis-engine-heading"><h2>Stockfish</h2><span>{w.engine.depth != null ? `Глибина ${w.engine.depth}` : ""}</span></div>
            {!w.engineEnabled ? <p className="analysis-note">Движок вимкнено. Увімкніть перемикач угорі для аналізу позиції.</p> : w.running ? <p role="status">Триває огляд партії. Аналіз позиції продовжиться після його завершення.</p> : w.engine.error ? <div role="alert"><p className="analysis-error">{w.engine.error}</p><Button variant="outline" onClick={w.engine.retry}>Спробувати ще раз</Button></div> : <>
              {w.engine.busy && <p className="analysis-note" role="status">Stockfish аналізує позицію…</p>}{w.engine.terminal && <p className="analysis-note">{w.engine.terminal.mate != null ? "Мат. Партію завершено." : "Нічийна позиція."}</p>}
              {(w.engine.result?.lines || []).map(result => { const moves = pvMoves(w.selected.fen, result.pv); return <div className="analysis-engine-line" key={result.multipv}><strong>{result.scoreMate != null ? `${result.scoreMate > 0 ? "+" : "−"}M${Math.abs(result.scoreMate)}` : result.scoreCp != null ? `${result.scoreCp > 0 ? "+" : ""}${(result.scoreCp / 100).toFixed(2)}` : "—"}</strong><div>{moves.slice(0, 12).map((move, i) => <button key={i} onClick={() => w.previewLine(w.selected.fen, result.pv, i)}>{move.label}</button>)}</div></div>; })}
              {!w.loaded && <p className="analysis-note">Імпортуйте позицію або зробіть хід на дошці.</p>}
            </>}<p className="analysis-note">Натисніть хід у лінії, щоб переглянути варіант на дошці.</p>
          </div></TabsContent>
          <TabsContent value="info" className="analysis-tab-content"><div className="analysis-info"><h2>Дані партії</h2>{headers.length ? <dl>{headers.map(([key, value]) => <div key={key}><dt>{HEADER_LABELS[key] || key}</dt><dd>{value}</dd></div>)}</dl> : <p className="analysis-note">У цій позиції немає даних про гравців або подію.</p>}<label htmlFor="current-fen">Поточний FEN</label><Textarea id="current-fen" readOnly value={w.displayedFen}/><Button size="sm" variant="outline" onClick={() => void copyText(w.displayedFen)}><Copy size={14}/>Копіювати FEN</Button></div></TabsContent>
        </Tabs>
        <EvaluationGraph report={w.review.report} index={w.index} onSelect={w.selectIndex}/>
        <footer className="analysis-save"><div><FolderClock size={16}/><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="sm" disabled={!w.accountId}>Останні аналізи</Button></DropdownMenuTrigger><DropdownMenuContent align="start">{w.sessions.data?.map(item => <DropdownMenuItem key={item.id} onSelect={() => w.navigate(`/analysis?session=${item.id}`)}>{item.title}</DropdownMenuItem>)}{!w.sessions.data?.length && <DropdownMenuItem disabled>{w.sessions.isPending ? "Завантаження…" : w.sessions.isError ? "Не вдалося завантажити" : "Збережених аналізів немає"}</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></div>{w.accountId ? <Button size="sm" disabled={w.saving || w.busy || !w.loaded} onClick={() => void w.save()}><Save size={15}/>{w.saving ? "Збереження…" : w.dirty ? "Зберегти зміни" : "Зберегти"}</Button> : <Button asChild variant="outline" size="sm"><Link to="/login">Увійти для збереження</Link></Button>}</footer>
      </aside>
    </div>
    <Dialog open={w.importOpen} onOpenChange={w.setImportOpen}><DialogContent className="analysis-import-dialog"><DialogHeader><DialogTitle>Імпорт партії або позиції</DialogTitle><DialogDescription>Вставте PGN чи FEN або відкрийте файл .pgn до 2 МБ.</DialogDescription></DialogHeader><label htmlFor="analysis-import">PGN або FEN</label><Textarea id="analysis-import" value={w.draft} onChange={event => w.setDraft(event.target.value)} rows={9} placeholder="Вставте запис партії або FEN…" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); void w.importFile(event.dataTransfer.files[0]); }}/><input ref={fileInput} type="file" accept=".pgn" className="sr-only" aria-label="Файл PGN" onChange={event => { void w.importFile(event.target.files?.[0]); event.target.value = ""; }}/>{w.importError && <p className="analysis-error" role="alert">{w.importError}</p>}<div className="analysis-small-actions"><Button variant="outline" onClick={() => fileInput.current?.click()}>Завантажити PGN-файл</Button><Button onClick={() => w.importDraft()}>Відкрити аналіз</Button></div>{w.accountId && <div className="analysis-import-recent"><h3>Останні партії</h3>{w.recent.isPending ? <p>Завантаження…</p> : w.recent.isError ? <p role="alert">Не вдалося завантажити партії.</p> : !w.recent.data?.length ? <p>Завершених партій ще немає.</p> : w.recent.data.map(game => <button key={game.id} onClick={() => { w.setImportOpen(false); w.navigate(`/analysis/${game.id}`); }}>{game.result} · {game.time_control || "Без часу"} · {new Date(game.created_at).toLocaleDateString("uk-UA")}</button>)}</div>}</DialogContent></Dialog>
    {w.editorOpen && <PositionEditor fen={w.selected.fen} onClose={() => w.setEditorOpen(false)} onApply={fen => { w.review.cancel(); w.replace(newDocument(fen)); w.setEditorOpen(false); w.setTab("engine"); }}/>}
    <Dialog open={w.settingsOpen} onOpenChange={w.setSettingsOpen}><DialogContent><DialogHeader><DialogTitle>Налаштування аналізу</DialogTitle><DialogDescription>Параметри перевірки поточної позиції.</DialogDescription></DialogHeader><div className="analysis-settings"><label>Швидкість і глибина<select aria-label="Режим аналізу" value={w.level} onChange={event => w.setLevel(event.target.value as EngineLevel)}>{Object.entries(ENGINE_LEVELS).map(([key, option]) => <option key={key} value={key}>{option.label}</option>)}</select></label><label>Кількість варіантів<select aria-label="Кількість варіантів" value={w.multiPv} onChange={event => w.setMultiPv(Number(event.target.value))}>{[1, 2, 3].map(value => <option key={value}>{value}</option>)}</select></label><label className="analysis-check">Показувати найкращий хід<Switch checked={w.bestArrow} onCheckedChange={w.setBestArrow}/></label><label>Назва аналізу<Input value={w.title} onChange={event => { w.setTitle(event.target.value); w.setDirty(true); }} maxLength={160}/></label><details><summary>Параметри рушія</summary><p>Stockfish у браузері: 1 потік, 16 МБ пам’яті. Ліміт глибини: {ENGINE_LEVELS[w.level].depth}; часу: {ENGINE_LEVELS[w.level].movetime / 1000} с. Досягнута глибина показується біля варіантів.</p></details></div></DialogContent></Dialog>
  </div>;
}
