import { useMemo, useState } from "react";
import { useNavigate, useSearchParams, Link } from "react-router-dom";
import { ArrowLeft, Copy, Download, Flag, Lightbulb, Pause, Play as PlayIcon, RefreshCw, SlidersHorizontal, Undo2 } from "lucide-react";
import type { Square } from "chess.js";
import ChessBoard from "@/components/ChessBoard";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/hooks/useAuth";
import { COMPUTER_LEVELS, parseTimeControl } from "@/features/play/preferences";
import { GameRoom } from "@/features/game-room/GameRoom";
import { GameControls, ConfirmAction } from "@/features/game-room/GameControls";
import { GameInfo } from "@/features/game-room/GameInfo";
import { useRoomPreferences } from "@/features/game-room/preferences";
import { capturedMaterial, readHistory, resultPresentation } from "@/features/game-room/rules";
import { useComputerGame } from "@/features/game-room/useComputerGame";
import { useTrainingHints } from "@/features/game-room/useTrainingHints";
import { copyPgn, downloadPgn } from "@/features/game-room/notation";
import type { Color, RoomPlayer } from "@/features/game-room/types";
export default function Play() {
    const [params] = useSearchParams();
    const navigate = useNavigate();
    const { user } = useAuth();
    const [preferences, updatePreferences] = useRoomPreferences();
    const [flipped, setFlipped] = useState(false);
    const [cursor, setCursor] = useState<number | null>(null);
    const [confirm, setConfirm] = useState<"resign" | "restart" | null>(null);
    const levelId = params.get("bot");
    const level = COMPUTER_LEVELS.find(item => item.id === levelId) || COMPUTER_LEVELS[2];
    const time = parseTimeControl(params.get("time"))?.value || ({ "1m": "1+0", "3m": "3+0", "5m": "5+0", "10m": "10+0", "15m": "15+0" } as Record<string, string>)[params.get("time") || ""] || "unlimited";
    const [color] = useState<Color>(() => params.get("color") === "b" ? "b" : params.get("color") === "random" && Math.random() < .5 ? "b" : "w");
    const name = user?.user_metadata?.display_name || user?.email?.split("@")[0] || "Гість";
    const config = useMemo(() => ({ color, timeControl: time, level: COMPUTER_LEVELS.indexOf(level) + 1, playerName: name, levelName: level.label }), [color, time, level, name]);
    const game = useComputerGame(config, preferences);
    const { view } = game;
    const history = useMemo(() => readHistory(view.pgn, view.fen), [view.pgn, view.fen]);
    const ended = view.result !== "*";
    const turn = history.game.turn();
    const playing = !ended && !view.paused;
    const reviewing = cursor != null;
    const canMove = playing && turn === color && !game.thinking && !reviewing;
    const hints = useTrainingHints(view.fen, canMove, preferences.evaluation);
    const fen = cursor == null ? view.fen : history.positions[cursor + 1] || view.fen;
    const last = history.verbose[cursor == null ? history.verbose.length - 1 : cursor];
    const seat = (seatColor: Color): RoomPlayer => ({ name: seatColor === color ? name : "Chess of Odesa Engine", color: seatColor, own: seatColor === color, computer: seatColor !== color, subtitle: seatColor === color ? (color === "w" ? "Білі · тренування" : "Чорні · тренування") : `${level.label}${level.rating ? ` · ≈${level.rating}` : ""}`, ...capturedMaterial(history.verbose, view.fen, seatColor), clock: { remainingMs: view.clocks[seatColor], asOf: view.clocks.asOf, running: playing && turn === seatColor, onFlag: game.flag } });
    const bottomColor = flipped ? (color === "w" ? "b" : "w") : color;
    const topColor = bottomColor === "w" ? "b" : "w";
    const restart = () => { setCursor(null); game.restart(); };
    const status = ended ? "Партію завершено" : view.paused ? "Партію призупинено" : game.error ? "Не вдалося отримати хід" : game.thinking ? "Комп’ютер думає…" : reviewing ? "Перегляд історії · годинник працює" : turn === color ? (history.game.isCheck() ? "Ваш хід · шах" : "Ваш хід") : "Хід комп’ютера";
    const controls = ended ? null : <GameControls more={[...(time === "unlimited" ? [] : [{ label: view.paused ? "Продовжити" : "Пауза", icon: view.paused ? <PlayIcon size={16}/> : <Pause size={16}/>, onClick: game.togglePause }]), { label: "Почати заново", icon: <RefreshCw size={16}/>, onClick: () => history.moves.length ? setConfirm("restart") : restart() }, { label: "Здатися", icon: <Flag size={16}/>, onClick: () => setConfirm("resign") }]}><Button variant="outline" disabled={!history.moves.length} onClick={() => { setCursor(null); game.undo(); }}><Undo2 size={16}/>Повернути</Button><Button variant="outline" disabled={!canMove || hints.busy} onClick={() => void hints.request()}><Lightbulb size={16}/>{hints.busy ? "Пошук…" : "Підказка"}</Button></GameControls>;
    const result = ended ? { ...resultPresentation(view.result, color, view.reason), result: view.result, id: view.id, pgn: view.pgn, players: { w: seat("w"), b: seat("b") }, startedAt: view.startedAt, finishedAt: view.finishedAt, onFullAnalysis: () => navigate("/analysis", { state: { pgn: view.pgn } }), actions: <><Button variant="outline" onClick={restart}><RefreshCw size={15}/>Зіграти ще раз</Button><Button asChild variant="outline"><Link to="/play?mode=computer"><SlidersHorizontal size={15}/>Змінити рівень</Link></Button><Button asChild variant="ghost"><Link to="/play"><ArrowLeft size={15}/>Назад до Грати</Link></Button></> } : undefined;
    const info = <GameInfo rows={[["Режим", "Проти комп’ютера"], ["Рівень", `${level.label}${level.rating ? ` · ≈${level.rating}` : ""}`], ["Рейтинг", "Тренування без зміни рейтингу"], ["Час", time === "unlimited" ? "Без часу" : time], ["Рушій", game.backend], ["Дата", new Date(view.startedAt).toLocaleString("uk-UA")], ["Ваш колір", color === "w" ? "Білі" : "Чорні"]]}><p>Сила рівня орієнтовна. Підказки доступні за вашим запитом.</p>{ended && <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => void copyPgn(view.pgn)}><Copy size={14}/>Копіювати PGN</Button><Button size="sm" variant="outline" onClick={() => downloadPgn(view.pgn, view.id)}><Download size={14}/>Завантажити PGN</Button></div>}</GameInfo>;
    return <><GameRoom mode="computer" title="Проти комп’ютера" timeControl={time} preferences={preferences} updatePreferences={updatePreferences} onFlip={() => setFlipped(value => !value)} top={seat(topColor)} bottom={seat(bottomColor)} moves={history.moves} cursor={cursor} onCursor={setCursor} status={status} statusTone={game.error || view.paused ? "is-warning" : game.thinking ? "is-thinking" : canMove ? "is-turn" : ""} info={info} controls={controls} result={result} evaluation={preferences.evaluation ? hints.evaluation : null} notice={game.error ? <div className="room-notice"><span>{game.error}</span><Button size="sm" variant="outline" onClick={game.retry}>Спробувати ще раз</Button></div> : hints.error ? <span>{hints.error}</span> : hints.hint ? <span>{hints.hint.stage === 1 ? "Спробуйте знайти хід виділеною фігурою." : "Підказка показує рекомендований хід."}</span> : null} board={size => <ChessBoard initialFen={fen} size={size} flipped={bottomColor === "b"} playerColor={color} interactive={canMove} onMove={(from, to, promotion) => game.move(from, to, promotion)} lastMoveSquares={last ? [last.from, last.to] : []} showLastMove={preferences.lastMove} showLegalMoves={preferences.legalMoves} showChecks autoQueen={preferences.autoQueen} confirmMove={preferences.confirmMove} animationDuration={preferences.animation ? 150 : 0} startSquares={hints.hint?.stage === 1 ? [hints.hint.from as Square] : []} customArrows={hints.hint?.stage === 2 ? [[hints.hint.from as Square, hints.hint.to as Square, "#315c9a"]] : []}/>}/><ConfirmAction open={confirm != null} onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm === "resign")
        game.resign();
    else
        restart(); setConfirm(null); }} title={confirm === "resign" ? "Ви справді хочете здатися?" : "Почати партію заново?"} description={confirm === "resign" ? "Поточна тренувальна партія завершиться поразкою." : "Позиція й годинники повернуться на початок."} confirm={confirm === "resign" ? "Здатися" : "Почати заново"}/></>;
}
